DROP DATABASE mvc;

CREATE DATABASE  IF NOT EXISTS mvc
CHARACTER SET utf8
COLLATE utf8_general_ci;

USE mvc;

CREATE TABLE IF NOT EXISTS posts(
    idpost INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    titulo VARCHAR(45),
    body VARCHAR(255),
    postCreated datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    iduser INT NOT NULL
);


CREATE TABLE IF NOT EXISTS users(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    date datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users
  ADD UNIQUE KEY email (email);

ALTER TABLE posts
ADD FOREIGN KEY (iduser) REFERENCES users(id);

